const CoursesData =[
   {
    id: 1,
    image:'./images/coursesScreen/physics.jpg',
    name:'Physics',
    category:'Class 12',
    class:'Class 11 & 12',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 2,
    image:'./images/coursesScreen/chemistry.jpg',
    name:'Chemistry',
    category:'Class 12',
    class:'Class 11 & 12',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 3,
    image:'./images/coursesScreen/mathsclass12.jpg',
    name:'Maths',
    category:'Class 12',
    class:'Class 11 & 12',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 4,
    image:'./images/coursesScreen/biology.jpg',
    name:'Biology',
    category:'Class 12',
    class:'Class 11 & 12',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 5,
    image:'./images/coursesScreen/science.jpg',
    name:'Science',
    category:'Class 10',
    class:'Class 9 & 10',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 6,
    image:'./images/coursesScreen/mathsclass10.jpg',
    name:'Maths',
    class:'Class 9 & 10',
    category:'Class 10',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 7,
    image:'./images/coursesScreen/englishclass12.jpg',
    name:'English',
    category:'Class 12',
    class:'Class 11 & 12',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 8,
    image:'./images/coursesScreen/english.jpg',
    name:'English',
    category:'Class 10',
    class:'Class 9 & 10',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 9,
    image:'./images/coursesScreen/datascience.jpg',
    name:'Data Science',
    category:'Professional',
    class:'Professional',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 10,
    image:'./images/coursesScreen/machineLearning.jpeg',
    name:'Machine Learning',
    category:'Professional',
    class:'Professional',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 11,
    image:'./images/coursesScreen/c.jpg',
    name:'C/C++',
    category:'Professional',
    class:'Professional',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
   {
    id: 12,
    image:'./images/coursesScreen/python.png',
    name:'Python',
    category:'Class 12',
    class:'Class 11 & 12',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt metus eu efficitur ultrices',
   },
]

export default CoursesData;